export { default as HomePage } from './home/home'
export { default as OnSalePage } from './onSale/on-sale'
export { default as NewArrivalsPage } from './newArrivals/new-arrivals'
export { default as SignIn } from './SignIn/SignIn'
export { default as NotFound } from './notFound/index'
export { default as ServerInternalPage } from './serverInternalPage/index'
